<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DiagnosisParametersSeeder extends Seeder
{



    protected $diagnosisParameters =[
    //----///
    ["id" => 1, "category" => 4,      "cardinality" => 1,  "name" => "Adenitis"],
    ["id" => 2, "category" => 4,      "cardinality" => 2,  "name" => "Alergia"],
    ["id" => 3, "category" => 4,      "cardinality" => 3,  "name" => "Amigdalitis"],
    ["id" => 4, "category" => 4,      "cardinality" => 4,  "name" => "Artritis"],
    ["id" => 5, "category" => 4,      "cardinality" => 5,  "name" => "Asma"],
    ["id" => 6, "category" => 4,      "cardinality" => 6,  "name" => "Bilharzia"],
    ["id" => 7, "category" => 4,      "cardinality" => 7,  "name" => "Blenorragia"],
    ["id" => 8, "category" => 4,      "cardinality" => 8,  "name" => "Bronquitis"],
    ["id" => 9, "category" => 4,      "cardinality" => 9,  "name" => "Buba"],
    ["id" => 10, "category" => 4,     "cardinality" => 10,  "name" => "Catarros"],
    ["id" => 11, "category" => 4,     "cardinality" => 11,  "name" => "Chagas"],
    ["id" => 12, "category" => 4,     "cardinality" => 12,  "name" => "Chancros"],
    ["id" => 13, "category" => 4,     "cardinality" => 13,  "name" => "Difteria"],
    ["id" => 14, "category" => 4,     "cardinality" => 14,  "name" => "Diarreas"],
    ["id" => 15, "category" => 4,     "cardinality" => 15,  "name" => "Hansen"],
    ["id" => 16, "category" => 4,     "cardinality" => 16,  "name" => "Influenzas"],
    ["id" => 17, "category" => 4,     "cardinality" => 17,  "name" => "Necatoriasis"],
    ["id" => 18, "category" => 4,     "cardinality" => 18,  "name" => "Necatoriasis"],
    ["id" => 19, "category" => 4,     "cardinality" => 19,  "name" => "Neumonía"],
    ["id" => 20, "category" => 4,     "cardinality" => 20,  "name" => "Otitis"],
    ["id" => 21, "category" => 4,     "cardinality" => 21,  "name" => "Paludismo"],
    ["id" => 22, "category" => 4,     "cardinality" => 22,  "name" => "Parásitos"],
    ["id" => 23, "category" => 4,     "cardinality" => 23,  "name" => "Parotiditis"],
    ["id" => 24, "category" => 4,     "cardinality" => 24,  "name" => "Pleuresía"],
    ["id" => 25, "category" => 4,     "cardinality" => 25,  "name" => "Quirúrgicos"],
    ["id" => 26, "category" => 4,     "cardinality" => 26,  "name" => "Rinofaringitis"],
    ["id" => 27, "category" => 4,     "cardinality" => 27,  "name" => "Rubéola"],
    ["id" => 28, "category" => 4,     "cardinality" => 28,  "name" => "Sarampión"],
    ["id" => 29, "category" => 4,     "cardinality" => 29,  "name" => "Sífilis"],
    ["id" => 30, "category" => 4,     "cardinality" => 30,  "name" => "Síndromes Disentéricos"],
    ["id" => 31, "category" => 4,     "cardinality" => 31,  "name" => "T.B.C."],
    ["id" => 32, "category" => 4,     "cardinality" => 32,  "name" => "Tifoidea"],
    ["id" => 33, "category" => 4,     "cardinality" => 33,  "name" => "Tosferina"],
    ["id" => 34, "category" => 4,     "cardinality" => 34,  "name" => "Traumatismos"],
    ["id" => 35, "category" => 4,     "cardinality" => 35,  "name" => "Vacunaciones"],
    ["id" => 36, "category" => 4,     "cardinality" => 36,  "name" => "Otros"],
        //----///
    ["id" => 37, "category" => 5,     "cardinality" => 1,  "name" => "Alergia"],
    ["id" => 38, "category" => 5,     "cardinality" => 2,  "name" => "Artritis"],
    ["id" => 39, "category" => 5,     "cardinality" => 3,  "name" => "Cáncer"],
    ["id" => 40, "category" => 5,     "cardinality" => 4,  "name" => "Cardio-vasculares"],
    ["id" => 41, "category" => 5,     "cardinality" => 5,  "name" => "Diabetes"],
    ["id" => 42, "category" => 5,     "cardinality" => 6,  "name" => "Enf. Digestivas"],
    ["id" => 43, "category" => 5,     "cardinality" => 7,  "name" => "Enf. Renales"],
    ["id" => 44, "category" => 5,     "cardinality" => 8,  "name" => "Intoxicaciones"],
    ["id" => 45, "category" => 5,     "cardinality" => 9,  "name" => "Neuromentales"],
    ["id" => 46, "category" => 5,     "cardinality" => 10,  "name" => "Sífilis"],
    ["id" => 47, "category" => 5,     "cardinality" => 11,  "name" => "T.B.C."],
    ["id" => 48, "category" => 5,     "cardinality" => 12,  "name" => "Otros"],
        //----///
    ["id" => 49, "category" => 6,     "cardinality" => 1,  "name" => "Alcohol"],
    ["id" => 50, "category" => 6,     "cardinality" => 2,  "name" => "Chimó"],
    ["id" => 51, "category" => 6,     "cardinality" => 3,  "name" => "Deportes"],
    ["id" => 52, "category" => 6,     "cardinality" => 4,  "name" => "Drogas"],
    ["id" => 53, "category" => 6,     "cardinality" => 5,  "name" => "Ocupación"],
    ["id" => 54, "category" => 6,     "cardinality" => 6,  "name" => "Problemas Familiares"],
    ["id" => 55, "category" => 6,     "cardinality" => 7,  "name" => "Rasgos Personales"],
    ["id" => 56, "category" => 6,     "cardinality" => 8,  "name" => "Sexuales"],
    ["id" => 57, "category" => 6,     "cardinality" => 9,  "name" => "Siesta"],
    ["id" => 58, "category" => 6,     "cardinality" => 10,  "name" => "Sueño"],
    ["id" => 59, "category" => 6,     "cardinality" => 11,  "name" => "Tabaco"],
    ["id" => 60, "category" => 6,     "cardinality" => 12,  "name" => "Otros"],

        //----///
    ["id" => 61, "category" => 7,     "cardinality" => 1,  "name" => "Aumento de Peso"],
    ["id" => 62, "category" => 7,     "cardinality" => 2,  "name" => "Fiebre"],
    ["id" => 63, "category" => 7,     "cardinality" => 3,  "name" => "Nutrición"],
    ["id" => 64, "category" => 7,     "cardinality" => 4,  "name" => "Pérdida de Peso"],
    ["id" => 65, "category" => 7,     "cardinality" => 5,  "name" => "Sudores Nocturnos"],
    ["id" => 66, "category" => 7,     "cardinality" => 6,  "name" => "Temblores"],
    ["id" => 67, "category" => 7,     "cardinality" => 7,  "name" => "Otros"],
        //----///
    ["id" => 68, "category" => 8,     "cardinality" => 1,  "name" => "Cianosis"],
    ["id" => 69, "category" => 8,     "cardinality" => 2,  "name" => "Edemas"],
    ["id" => 70, "category" => 8,     "cardinality" => 3,  "name" => "Erupciones"],
    ["id" => 71, "category" => 8,     "cardinality" => 4,  "name" => "Pigmentaciones"],
    ["id" => 72, "category" => 8,     "cardinality" => 5,  "name" => "Prurito"],
    ["id" => 73, "category" => 8,     "cardinality" => 6,  "name" => "Otros"],
        //----///
    ["id" => 74, "category" => 9,     "cardinality" => 1,  "name" => "Caída del Cabello"],
    ["id" => 75, "category" => 9,     "cardinality" => 2,  "name" => "Cefalea"],
    ["id" => 76, "category" => 9,     "cardinality" => 3,  "name" => "Mareos"],
    ["id" => 77, "category" => 9,     "cardinality" => 4,  "name" => "Síncope"],
    ["id" => 78, "category" => 9,     "cardinality" => 5,  "name" => "Traumas"],
    ["id" => 79, "category" => 9,     "cardinality" => 6,  "name" => "Otros"],
        //----///
    ["id" => 80, "category" => 10,    "cardinality" => 1,  "name" => "Amaurosis"],
    ["id" => 81, "category" => 10,    "cardinality" => 2,  "name" => "Anteojos"],
    ["id" => 82, "category" => 10,    "cardinality" => 3,  "name" => "Cansancio Ocular"],
    ["id" => 83, "category" => 10,    "cardinality" => 4,  "name" => "Diplopia"],
    ["id" => 84, "category" => 10,    "cardinality" => 5,  "name" => "Dolor"],
    ["id" => 85, "category" => 10,    "cardinality" => 6,  "name" => "Fotofobia"],
    ["id" => 86, "category" => 10,    "cardinality" => 7,  "name" => "Lagrimeo"],
    ["id" => 87, "category" => 10,    "cardinality" => 8,  "name" => "Otros"],
        //----///
    ["id" => 88, "category" => 11,    "cardinality" => 1,  "name" => "Dolor"],
    ["id" => 89, "category" => 11,    "cardinality" => 2,  "name" => "Secreciones"],
    ["id" => 90, "category" => 11,    "cardinality" => 3,  "name" => "Sordera"],
    ["id" => 91, "category" => 11,    "cardinality" => 4,  "name" => "Tinitus"],
    ["id" => 92, "category" => 11,    "cardinality" => 5,  "name" => "Vértigo"],
    ["id" => 93, "category" => 11,    "cardinality" => 6,  "name" => "Otros"],
        //----///
    ["id" => 94, "category" => 12,    "cardinality" => 1,  "name" => "Catarros"],
    ["id" => 95, "category" => 12,    "cardinality" => 2,  "name" => "Epistaxis"],
    ["id" => 96, "category" => 12,    "cardinality" => 3,  "name" => "Obstrucciones"],
    ["id" => 97, "category" => 12,    "cardinality" => 4,  "name" => "Secreción Nasal"],
    ["id" => 98, "category" => 12,    "cardinality" => 5,  "name" => "Sinusitis"],
    ["id" => 99, "category" => 12,    "cardinality" => 6,  "name" => "Otros"],
        //----///
    ["id" => 100, "category" => 13,   "cardinality" => 1,  "name" => "Dientes"],
    ["id" => 101, "category" => 13,   "cardinality" => 2,  "name" => "Halitosis"],
    ["id" => 102, "category" => 13,   "cardinality" => 3,  "name" => "Mucosas"],
    ["id" => 103, "category" => 13,   "cardinality" => 4,  "name" => "Otros"],
        //----///
    ["id" => 104, "category" => 14,   "cardinality" => 1,  "name" => "Disfagia"],
    ["id" => 105, "category" => 14,   "cardinality" => 2,  "name" => "Dolor"],
    ["id" => 106, "category" => 14,   "cardinality" => 3,  "name" => "Ronquera"],
    ["id" => 107, "category" => 14,   "cardinality" => 4,  "name" => "Otros"],
        //----///
    ["id" => 108, "category" => 15,   "cardinality" => 1,  "name" => "Disnea"],
    ["id" => 109, "category" => 15,   "cardinality" => 2,  "name" => "Dolor en el Pecho"],
    ["id" => 110, "category" => 15,   "cardinality" => 3,  "name" => "Esputos"],
    ["id" => 111, "category" => 15,   "cardinality" => 4,  "name" => "Hemoptisis"],
    ["id" => 112, "category" => 15,   "cardinality" => 5,  "name" => "Tos"],
    ["id" => 113, "category" => 15,   "cardinality" => 6,  "name" => "Otros"],
        //----///
    ["id" => 114, "category" => 16,   "cardinality" => 1,  "name" => "Artralgias"],
    ["id" => 115, "category" => 16,   "cardinality" => 2,  "name" => "Debilidad"],
    ["id" => 116, "category" => 16,   "cardinality" => 3,  "name" => "Dolores Oseos"],
    ["id" => 117, "category" => 16,   "cardinality" => 4,  "name" => "Deformidades"],
    ["id" => 118, "category" => 16,   "cardinality" => 5,  "name" => "Otros"],
        //----///
    ["id" => 119, "category" => 17,   "cardinality" => 1,  "name" => "Angustias"],
    ["id" => 120, "category" => 17,   "cardinality" => 2,  "name" => "Disnea"],
    ["id" => 121, "category" => 17,   "cardinality" => 3,  "name" => "Dolor"],
    ["id" => 122, "category" => 17,   "cardinality" => 4,  "name" => "Palpitaciones"],
    ["id" => 123, "category" => 17,   "cardinality" => 5,  "name" => "Taquicardia"],
    ["id" => 124, "category" => 17,   "cardinality" => 6,  "name" => "Vértigos"],
    ["id" => 125, "category" => 17,   "cardinality" => 7,  "name" => "Claudicación"],
    ["id" => 126, "category" => 17,   "cardinality" => 8,  "name" => "Trastornos Parestésicos"],
    ["id" => 127, "category" => 17,   "cardinality" => 9,  "name" => "Varicosidades"],
    ["id" => 128, "category" => 17,   "cardinality" => 10,  "name" => "Otros"],
        //----///
    ["id" => 129, "category" => 18,   "cardinality" => 1,  "name" => "Apetito"],
    ["id" => 130, "category" => 18,   "cardinality" => 2,  "name" => "Constipación"],
    ["id" => 131, "category" => 18,   "cardinality" => 3,  "name" => "Diarrea"],
    ["id" => 132, "category" => 18,   "cardinality" => 4,  "name" => "Dolor"],
    ["id" => 133, "category" => 18,   "cardinality" => 5,  "name" => "Heces; Tipo\n- Color\n- Mucosidad\n- Sangre"],

    ["id" => 134, "category" => 18,   "cardinality" => 6,  "name" => "Eructos"],
    ["id" => 135, "category" => 18,   "cardinality" => 7,  "name" => "Flatulencia"],
    ["id" => 136, "category" => 18,   "cardinality" => 8,  "name" => "Hemorroides"],
    ["id" => 137, "category" => 18,   "cardinality" => 9,  "name" => "Hernias"],
    ["id" => 138, "category" => 18,   "cardinality" => 10,  "name" => "Malestar"],
    ["id" => 139, "category" => 18,   "cardinality" => 11,  "name" => "Náuseas"],
    ["id" => 140, "category" => 18,   "cardinality" => 12,  "name" => "Parásitos"],
    ["id" => 141, "category" => 18,   "cardinality" => 13,  "name" => "Pirosis"],
    ["id" => 142, "category" => 18,   "cardinality" => 14,  "name" => "Vómitos"],
    ["id" => 143, "category" => 18,   "cardinality" => 15,  "name" => "Otros"],
        //----///
    ["id" => 144, "category" => 19,   "cardinality" => 1,  "name" => "Dolor"],
    ["id" => 145, "category" => 19,   "cardinality" => 2,  "name" => "Enuresis"],
    ["id" => 146, "category" => 19,   "cardinality" => 3,  "name" => "Hematuria"],
    ["id" => 147, "category" => 19,   "cardinality" => 4,  "name" => "Incontinencia"],
    ["id" => 148, "category" => 19,   "cardinality" => 5,  "name" => "Micciones"],
    ["id" => 149, "category" => 19,   "cardinality" => 6,  "name" => "Nicturia"],
    ["id" => 150, "category" => 19,   "cardinality" => 7,  "name" => "Piuria"],
    ["id" => 151, "category" => 19,   "cardinality" => 8,  "name" => "Secreciones"],
    ["id" => 152, "category" => 19,   "cardinality" => 9,  "name" => "Ulceras"],
    ["id" => 153, "category" => 19,   "cardinality" => 10,  "name" => "Otros"],
        //----///
    ["id" => 154, "category" => 20,   "cardinality" => 1,  "name" => "Menarquia"],
    ["id" => 155, "category" => 20,   "cardinality" => 2,  "name" => "Abortos"],
    ["id" => 156, "category" => 20,   "cardinality" => 3,  "name" => "Partos"],
    ["id" => 157, "category" => 20,   "cardinality" => 4,  "name" => "Dispareunia"],
    ["id" => 158, "category" => 20,   "cardinality" => 5,  "name" => "Frigidez"],
    ["id" => 159, "category" => 20,   "cardinality" => 6,  "name" => "Menopausia"],
    ["id" => 160, "category" => 20,   "cardinality" => 7,  "name" => "Reglas; Tipo\n- Cantidad\n- Dolor\n- Ultima Regla"],

    ["id" => 161, "category" => 20,   "cardinality" => 8,  "name" => "Flujo"],
    ["id" => 162, "category" => 20,   "cardinality" => 9,  "name" => "Otros"],
        //----///
    ["id" => 163, "category" => 21,   "cardinality" => 1,  "name" => "Convulsiones"],
    ["id" => 164, "category" => 21,   "cardinality" => 2,  "name" => "Estática"],
    ["id" => 165, "category" => 21,   "cardinality" => 3,  "name" => "Estado Emocional"],
    ["id" => 166, "category" => 21,   "cardinality" => 4,  "name" => "Marcha"],
    ["id" => 167, "category" => 21,   "cardinality" => 5,  "name" => "Parálisis"],
    ["id" => 168, "category" => 21,   "cardinality" => 6,  "name" => "Temblor"],
    ["id" => 169, "category" => 21,   "cardinality" => 7,  "name" => "Tics"],
    ["id" => 170, "category" => 21,   "cardinality" => 8,  "name" => "Tipo de Personalidad"],
    ["id" => 171, "category" => 21,   "cardinality" => 9,  "name" => "Otros"],


        //----///
    ["id" => 172, "category" => 22,   "cardinality" => 1,  "name" => "Color"],
    ["id" => 173, "category" => 22,   "cardinality" => 2,  "name" => "Humedad"],
    ["id" => 174, "category" => 22,   "cardinality" => 3,  "name" => "Contextura"],
    ["id" => 175, "category" => 22,   "cardinality" => 4,  "name" => "Temperatura"],
    ["id" => 176, "category" => 22,   "cardinality" => 5,  "name" => "Pigmentación"],
    ["id" => 177, "category" => 22,   "cardinality" => 6,  "name" => "Equimosis"],
    ["id" => 178, "category" => 22,   "cardinality" => 7,  "name" => "Cianosis"],
    ["id" => 179, "category" => 22,   "cardinality" => 8,  "name" => "Petequias"],
    ["id" => 180, "category" => 22,   "cardinality" => 9,  "name" => "Erupción"],
    ["id" => 181, "category" => 22,   "cardinality" => 10,  "name" => "Uñas"],
    ["id" => 182, "category" => 22,   "cardinality" => 11,  "name" => "Nódulos"],
    ["id" => 183, "category" => 22,   "cardinality" => 12,  "name" => "Vascularización"],
    ["id" => 184, "category" => 22,   "cardinality" => 13,  "name" => "Cicatrices"],
    ["id" => 185, "category" => 22,   "cardinality" => 14,  "name" => "Fístulas"],
    ["id" => 186, "category" => 22,   "cardinality" => 15,  "name" => "Ulceras"],
    ["id" => 187, "category" => 22,   "cardinality" => 16,  "name" => "Otros"],
        //----///
    ["id" => 188, "category" => 23,   "cardinality" => 1,  "name" => "Configuración"],
    ["id" => 189, "category" => 23,   "cardinality" => 2,  "name" => "Fontanelas"],
    ["id" => 190, "category" => 23,   "cardinality" => 3,  "name" => "Reblandecimiento"],
    ["id" => 191, "category" => 23,   "cardinality" => 4,  "name" => "Circunferencia"],
    ["id" => 192, "category" => 23,   "cardinality" => 5,  "name" => "Dolor"],
    ["id" => 193, "category" => 23,   "cardinality" => 6,  "name" => "Cabellos"],
    ["id" => 194, "category" => 23,   "cardinality" => 7,  "name" => "Otros"],
        //----///
    ["id" => 195, "category" => 24,   "cardinality" => 1,  "name" => "Conjuntiva"],
    ["id" => 196, "category" => 24,   "cardinality" => 2,  "name" => "Esclerótica"],
    ["id" => 197, "category" => 24,   "cardinality" => 3,  "name" => "Córnea"],
    ["id" => 198, "category" => 24,   "cardinality" => 4,  "name" => "Pupilas"],
    ["id" => 199, "category" => 24,   "cardinality" => 5,  "name" => "Movimientos"],
    ["id" => 200, "category" => 24,   "cardinality" => 6,  "name" => "Desviación"],
    ["id" => 201, "category" => 24,   "cardinality" => 7,  "name" => "Nistagmus"],
    ["id" => 202, "category" => 24,   "cardinality" => 8,  "name" => "Ptosis"],
    ["id" => 203, "category" => 24,   "cardinality" => 9,  "name" => "Exoftalmos"],
    ["id" => 204, "category" => 24,   "cardinality" => 10,  "name" => "Agudeza Visual"],
    ["id" => 205, "category" => 24,   "cardinality" => 11,  "name" => "Oftalmoscópicos"],
    ["id" => 206, "category" => 24,   "cardinality" => 12,  "name" => "Otros"],
        //----///
    ["id" => 207, "category" => 25,   "cardinality" => 1,  "name" => "Pabellón"],
    ["id" => 208, "category" => 25,   "cardinality" => 2,  "name" => "Conducto Externo"],
    ["id" => 209, "category" => 25,   "cardinality" => 3,  "name" => "Tímpano"],
    ["id" => 210, "category" => 25,   "cardinality" => 4,  "name" => "Audición"],
    ["id" => 211, "category" => 25,   "cardinality" => 5,  "name" => "Secreciones"],
    ["id" => 212, "category" => 25,   "cardinality" => 6,  "name" => "Mastoides"],
    ["id" => 213, "category" => 25,   "cardinality" => 7,  "name" => "Dolor"],
    ["id" => 214, "category" => 25,   "cardinality" => 8,  "name" => "Otros"],
        //----///
    ["id" => 215, "category" => 26,   "cardinality" => 1,  "name" => "Fosas Nasales"],
    ["id" => 216, "category" => 26,   "cardinality" => 2,  "name" => "Mucosa"],
    ["id" => 217, "category" => 26,   "cardinality" => 3,  "name" => "Tabique"],
    ["id" => 218, "category" => 26,   "cardinality" => 4,  "name" => "Meatos"],
    ["id" => 219, "category" => 26,   "cardinality" => 5,  "name" => "Diafanoscopia"],
    ["id" => 220, "category" => 26,   "cardinality" => 6,  "name" => "Sensibilidad de los Senos"],
    ["id" => 221, "category" => 26,   "cardinality" => 7,  "name" => "Secreción Nasal"],
    ["id" => 222, "category" => 26,   "cardinality" => 8,  "name" => "Otros"],
        //----///
    ["id" => 223, "category" => 27,   "cardinality" => 1,  "name" => "Aliento"],
    ["id" => 224, "category" => 27,   "cardinality" => 2,  "name" => "Labios"],
    ["id" => 225, "category" => 27,   "cardinality" => 3,  "name" => "Dientes"],
    ["id" => 226, "category" => 27,   "cardinality" => 4,  "name" => "Encías"],
    ["id" => 227, "category" => 27,   "cardinality" => 5,  "name" => "Mucosas"],
    ["id" => 228, "category" => 27,   "cardinality" => 6,  "name" => "Lengua"],
    ["id" => 229, "category" => 27,   "cardinality" => 7,  "name" => "Conductos Salivares"],
    ["id" => 230, "category" => 27,   "cardinality" => 8,  "name" => "Parálisis y trismo"],
    ["id" => 231, "category" => 27,   "cardinality" => 9,  "name" => "Otros"],
        //----///
    ["id" => 232, "category" => 28,   "cardinality" => 1,  "name" => "Amaurosis"],
    ["id" => 233, "category" => 28,   "cardinality" => 2,  "name" => "Anteojos"],
    ["id" => 234, "category" => 28,   "cardinality" => 3,  "name" => "Cansancio Ocular"],
    ["id" => 235, "category" => 28,   "cardinality" => 4,  "name" => "Dolor"],
    ["id" => 236, "category" => 28,   "cardinality" => 5,  "name" => "Fotofobia"],
    ["id" => 237, "category" => 28,   "cardinality" => 6,  "name" => "Lagrimeo"],
        //----///
    ["id" => 238, "category" => 29,   "cardinality" => 1,  "name" => "Movilidad"],
    ["id" => 239, "category" => 29,   "cardinality" => 2,  "name" => "Ganglios"],
    ["id" => 240, "category" => 29,   "cardinality" => 3,  "name" => "Tiroides"],
    ["id" => 241, "category" => 29,   "cardinality" => 4,  "name" => "Vasos"],
    ["id" => 242, "category" => 29,   "cardinality" => 5,  "name" => "Tráquea"],
    ["id" => 243, "category" => 29,   "cardinality" => 6,  "name" => "Otros"],
        //----///
    ["id" => 244, "category" => 30,   "cardinality" => 1,  "name" => "Cervicales"],
    ["id" => 245, "category" => 30,   "cardinality" => 2,  "name" => "Occipitales"],
    ["id" => 246, "category" => 30,   "cardinality" => 3,  "name" => "Supraclaviculares"],
    ["id" => 247, "category" => 30,   "cardinality" => 4,  "name" => "Axilares"],
    ["id" => 248, "category" => 30,   "cardinality" => 5,  "name" => "Epitrocleares"],
    ["id" => 249, "category" => 30,   "cardinality" => 6,  "name" => "Inguinales"],
    ["id" => 250, "category" => 30,   "cardinality" => 7,  "name" => "Otros"],
        //----///
    ["id" => 251, "category" => 31,   "cardinality" => 1,  "name" => "Forma"],
    ["id" => 252, "category" => 31,   "cardinality" => 2,  "name" => "Simetría"],
    ["id" => 253, "category" => 31,   "cardinality" => 3,  "name" => "Expansión"],
    ["id" => 254, "category" => 31,   "cardinality" => 4,  "name" => "Palpación"],
    ["id" => 255, "category" => 31,   "cardinality" => 5,  "name" => "Respiración"],
    ["id" => 256, "category" => 31,   "cardinality" => 6,  "name" => "Otros"],
        //----///
    ["id" => 257, "category" => 32,   "cardinality" => 1,  "name" => "Nódulos"],
    ["id" => 258, "category" => 32,   "cardinality" => 2,  "name" => "Secreciones"],
    ["id" => 259, "category" => 32,   "cardinality" => 3,  "name" => "Pezones"],
    ["id" => 260, "category" => 32,   "cardinality" => 4,  "name" => "Otros"],
        //----///
    ["id" => 261, "category" => 33,   "cardinality" => 1,  "name" => "Fremito"],
    ["id" => 262, "category" => 33,   "cardinality" => 2,  "name" => "Percusión"],
    ["id" => 263, "category" => 33,   "cardinality" => 3,  "name" => "Auscultación"],
    ["id" => 264, "category" => 33,   "cardinality" => 4,  "name" => "Ruidos Adventicios"],
    ["id" => 265, "category" => 33,   "cardinality" => 5,  "name" => "Pectoriloquia Afona"],
    ["id" => 266, "category" => 33,   "cardinality" => 6,  "name" => "Broncofonia"],
    ["id" => 267, "category" => 33,   "cardinality" => 7,  "name" => "Otros"],
        //----///
    ["id" => 268, "category" => 34,   "cardinality" => 1,  "name" => "Latido de la Punta"],
    ["id" => 269, "category" => 34,   "cardinality" => 2,  "name" => "Thrill"],
    ["id" => 270, "category" => 34,   "cardinality" => 3,  "name" => "Pulsación"],
    ["id" => 271, "category" => 34,   "cardinality" => 4,  "name" => "Ritmo"],
    ["id" => 272, "category" => 34,   "cardinality" => 5,  "name" => "Ruidos"],
    ["id" => 273, "category" => 34,   "cardinality" => 6,  "name" => "Galopes"],
    ["id" => 274, "category" => 34,   "cardinality" => 7,  "name" => "Frotes"],
    ["id" => 275, "category" => 34,   "cardinality" => 8,  "name" => "Otros"],
        //----///
    ["id" => 276, "category" => 35,   "cardinality" => 1,  "name" => "Pulso"],
    ["id" => 277, "category" => 35,   "cardinality" => 2,  "name" => "Paredes Vasculares"],
    ["id" => 278, "category" => 35,   "cardinality" => 3,  "name" => "Caracteres"],
    ["id" => 279, "category" => 35,   "cardinality" => 4,  "name" => "Otros"],
        //----///
    ["id" => 280, "category" => 36,   "cardinality" => 1,  "name" => "Aspecto"],
    ["id" => 281, "category" => 36,   "cardinality" => 2,  "name" => "Circunferencia"],
    ["id" => 282, "category" => 36,   "cardinality" => 3,  "name" => "Peristalsis"],
    ["id" => 283, "category" => 36,   "cardinality" => 4,  "name" => "Cicatrices"],
    ["id" => 284, "category" => 36,   "cardinality" => 5,  "name" => "Defensa"],
    ["id" => 285, "category" => 36,   "cardinality" => 6,  "name" => "Sensibilidad"],
    ["id" => 286, "category" => 36,   "cardinality" => 7,  "name" => "Contractura"],
    ["id" => 287, "category" => 36,   "cardinality" => 8,  "name" => "Tumoraciones"],
    ["id" => 288, "category" => 36,   "cardinality" => 9,  "name" => "Ascitis"],
    ["id" => 289, "category" => 36,   "cardinality" => 10,  "name" => "Hígado"],
    ["id" => 290, "category" => 36,   "cardinality" => 11,  "name" => "Riñones"],
    ["id" => 291, "category" => 36,   "cardinality" => 12,  "name" => "Bazo"],
    ["id" => 292, "category" => 36,   "cardinality" => 13,  "name" => "Hernias"],
    ["id" => 293, "category" => 36,   "cardinality" => 14,  "name" => "Otros"],
        //----///
    // ["id" => 294, "category" => 37,   "cardinality" => 1,  "name" => "Cicatrices"],
    // ["id" => 295, "category" => 37,   "cardinality" => 2,  "name" => "Lesiones"],
    // ["id" => 296, "category" => 37,   "cardinality" => 3,  "name" => "Secreciones"],
    // ["id" => 297, "category" => 37,   "cardinality" => 4,  "name" => "Escroto"],
    // ["id" => 298, "category" => 37,   "cardinality" => 5,  "name" => "Epidídimo"],
    // ["id" => 299, "category" => 37,   "cardinality" => 6,  "name" => "Deferentes"],
    // ["id" => 300, "category" => 37,   "cardinality" => 7,  "name" => "Testículos"],
    // ["id" => 301, "category" => 37,   "cardinality" => 8,  "name" => "Próstata"],
    // ["id" => 302, "category" => 37,   "cardinality" => 9,  "name" => "Seminales"],
    // ["id" => 303, "category" => 37,   "cardinality" => 10,  "name" => "Otros"],
        //----///
    ["id" => 304, "category" => 38,   "cardinality" => 1,  "name" => "Labios"],
    ["id" => 305, "category" => 38,   "cardinality" => 2,  "name" => "Bartholino"],
    ["id" => 306, "category" => 38,   "cardinality" => 3,  "name" => "Periné"],
    ["id" => 307, "category" => 38,   "cardinality" => 4,  "name" => "Vagina"],
    ["id" => 308, "category" => 38,   "cardinality" => 5,  "name" => "Cuello"],
    ["id" => 309, "category" => 38,   "cardinality" => 6,  "name" => "Utero"],
    ["id" => 310, "category" => 38,   "cardinality" => 7,  "name" => "Anexos"],
    ["id" => 311, "category" => 38,   "cardinality" => 8,  "name" => "Parametrios"],
    ["id" => 312, "category" => 38,   "cardinality" => 9,  "name" => "Douglas"],
    ["id" => 313, "category" => 38,   "cardinality" => 10,  "name" => "Otros"],
        //----///
    ["id" => 314, "category" => 39,   "cardinality" => 1,  "name" => "Fisuras"],
    ["id" => 315, "category" => 39,   "cardinality" => 2,  "name" => "Fístulas"],
    ["id" => 316, "category" => 39,   "cardinality" => 3,  "name" => "Hemorroides"],
    ["id" => 317, "category" => 39,   "cardinality" => 4,  "name" => "Esfínter"],
    ["id" => 318, "category" => 39,   "cardinality" => 5,  "name" => "Tumoraciones"],
    ["id" => 319, "category" => 39,   "cardinality" => 6,  "name" => "Prolapso"],
    ["id" => 320, "category" => 39,   "cardinality" => 7,  "name" => "Heces"],
    ["id" => 321, "category" => 39,   "cardinality" => 8,  "name" => "Otros"],
        //----///
    ["id" => 322, "category" => 40,   "cardinality" => 1,  "name" => "Deformidades"],
    ["id" => 323, "category" => 40,   "cardinality" => 2,  "name" => "Inflamaciones"],
    ["id" => 324, "category" => 40,   "cardinality" => 3,  "name" => "Rubicundes"],
    ["id" => 325, "category" => 40,   "cardinality" => 4,  "name" => "Sensibilidad"],
    ["id" => 326, "category" => 40,   "cardinality" => 5,  "name" => "Movimientos"],
    ["id" => 327, "category" => 40,   "cardinality" => 6,  "name" => "Masas Musculares"],
    ["id" => 328, "category" => 40,   "cardinality" => 7,  "name" => "Otros"],
        //----///
    ["id" => 329, "category" => 41,   "cardinality" => 1,  "name" => "Color"],
    ["id" => 330, "category" => 41,   "cardinality" => 2,  "name" => "Edema"],
    ["id" => 331, "category" => 41,   "cardinality" => 3,  "name" => "Temblor"],
    ["id" => 332, "category" => 41,   "cardinality" => 4,  "name" => "Deformidades"],
    ["id" => 333, "category" => 41,   "cardinality" => 5,  "name" => "Ulceras"],
    ["id" => 334, "category" => 41,   "cardinality" => 6,  "name" => "Várices"],
    ["id" => 335, "category" => 41,   "cardinality" => 7,  "name" => "Otros"],
        //----///
    ["id" => 336, "category" => 42,   "cardinality" => 1,  "name" => "Sensibilidad Objetiva"],
    ["id" => 337, "category" => 42,   "cardinality" => 2,  "name" => "Motilidad"],
    ["id" => 338, "category" => 42,   "cardinality" => 3,  "name" => "Reflectividad"],
    ["id" => 339, "category" => 42,   "cardinality" => 4,  "name" => "Escritura"],
    ["id" => 340, "category" => 42,   "cardinality" => 5,  "name" => "Tróficos"],
    ["id" => 341, "category" => 42,   "cardinality" => 6,  "name" => "Marcha"],
    ["id" => 342, "category" => 42,   "cardinality" => 7,  "name" => "Romberh"],
    ["id" => 343, "category" => 42,   "cardinality" => 8,  "name" => "Orientación"],
    ["id" => 344, "category" => 42,   "cardinality" => 9,  "name" => "Lenguaje"],
    ["id" => 345, "category" => 42,   "cardinality" => 10,  "name" => "Coordinación"],
    ["id" => 346, "category" => 42,   "cardinality" => 11,  "name" => "Otro"],
    ];



    protected $diagnosisParamteresCategories = [
    ["id" => 1,   "cardinality" => 1,    "name" => "ANTECEDENTES" ],
    ["id" => 2,   "cardinality" => 2,    "name" => "EXAMEN FUNCIONAL" ],
    ["id" => 3,   "cardinality" => 3,    "name" => "EXAMEN FÍSICO", "subtitle"=>"(Datos Objetivos)" ],


    ["id" => 4, "parent_id"=> 1,  "cardinality" => 1,    "name" => "ANTECEDENTES PERSONALES"],
    ["id" => 5, "parent_id"=> 1,  "cardinality" => 2,    "name" => "ANTECEDENTES FAMILIARES", "subtitle" => "ESTADO DE SALUD O CAUSA DE LA MUERTE DE LOS PADRES, HERMANOS, HIJOS Y OTROS FAMILIARES"],
    ["id" => 6, "parent_id"=> 1,  "cardinality" => 3,    "name" => "HÁBITOS PSICOBIOLÓGICOS"],

    ["id" => 7,  "parent_id"=> 2, "cardinality" => 4,    "name" => "GENERAL"],
    ["id" => 8,  "parent_id"=> 2, "cardinality" => 5,    "name" => "PIEL"],
    ["id" => 9,  "parent_id"=> 2, "cardinality" => 6,    "name" => "CABEZA"],
    ["id" => 10, "parent_id"=> 2, "cardinality" => 7,    "name" => "OJOS"],
    ["id" => 11, "parent_id"=> 2, "cardinality" => 8,    "name" => "OIDOS"],
    ["id" => 12, "parent_id"=> 2, "cardinality" => 9,    "name" => "NARIZ"],
    ["id" => 13, "parent_id"=> 2, "cardinality" => 10,  "name" => "BOCA"],
    ["id" => 14, "parent_id"=> 2, "cardinality" => 11,  "name" => "GARGANTA"],
    ["id" => 15, "parent_id"=> 2, "cardinality" => 12,  "name" => "RESPIRATORIO"],
    ["id" => 16, "parent_id"=> 2, "cardinality" => 13,  "name" => "OSTEOMUSCULAR"],
    ["id" => 17, "parent_id"=> 2, "cardinality" => 14,  "name" => "CARDIOVASCULAR"],
    ["id" => 18, "parent_id"=> 2, "cardinality" => 15,  "name" => "GASTROINTESTINAL"],
    ["id" => 19, "parent_id"=> 2, "cardinality" => 16,  "name" => "GENITOURINARIO"],
    ["id" => 20, "parent_id"=> 2, "cardinality" => 17,  "name" => "GINECOLÓGICOS"],
    ["id" => 21, "parent_id"=> 2, "cardinality" => 18,  "name" => "NERVIOSO Y MENTAL"],

    ["id" => 22, "parent_id"=> 3, "cardinality" => 1,   "name" => "PIEL"],
    ["id" => 23, "parent_id"=> 3, "cardinality" => 2,   "name" => "CABEZA"],
    ["id" => 24, "parent_id"=> 3, "cardinality" => 3,   "name" => "OJOS"],
    ["id" => 25, "parent_id"=> 3, "cardinality" => 4,   "name" => "OIDOS"],
    ["id" => 26, "parent_id"=> 3, "cardinality" => 5,   "name" => "NARIZ"],
    ["id" => 27, "parent_id"=> 3, "cardinality" => 6,   "name" => "BOCA"],
    ["id" => 28, "parent_id"=> 3, "cardinality" => 7,   "name" => "FARINGE"],
    ["id" => 29, "parent_id"=> 3, "cardinality" => 8,   "name" => "CUELLO"],
    ["id" => 30, "parent_id"=> 3, "cardinality" => 9,   "name" => "GANGLIOS LINFÁTICOS"],
    ["id" => 31, "parent_id"=> 3, "cardinality" => 10,  "name" => "TORAX"],
    ["id" => 32, "parent_id"=> 3, "cardinality" => 11,  "name" => "SENOS"],
    ["id" => 33, "parent_id"=> 3, "cardinality" => 12,  "name" => "PULMONES"],
    ["id" => 34, "parent_id"=> 3, "cardinality" => 13,  "name" => "CORAZÓN"],
    ["id" => 35, "parent_id"=> 3, "cardinality" => 14,  "name" => "VASOS SANGUÍNEOS"],
    ["id" => 36, "parent_id"=> 3, "cardinality" => 15,  "name" => "ABDOMEN"],
    // ["id" => 37, "parent_id"=> 3, "cardinality" => 16,  "name" => "GENITALES MASCULINOS"],
    ["id" => 38, "parent_id"=> 3, "cardinality" => 17,  "name" => "GENITALES FEMENINOS"],
    ["id" => 39, "parent_id"=> 3, "cardinality" => 18,  "name" => "RECTO"],
    ["id" => 40, "parent_id"=> 3, "cardinality" => 19,  "name" => "HUESOS, ARTICULACIONES, MÚSCULOS"],
    ["id" => 41, "parent_id"=> 3, "cardinality" => 20,  "name" => "EXTREMIDADES"],
    ["id" => 42, "parent_id"=> 3, "cardinality" => 21,  "name" => "NEUROLÓGICO Y PSÍQUICO"],
    ];





    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        foreach($this->diagnosisParamteresCategories as $category){
            \DB::table('diagnosis_parameters_categories')->insert(
                [
                    'id' => $category['id'],
                    'name' => $category['name'],
                    'subtitle' => $category['subtitle'] ?? null,
                    'cardinality' => $category['cardinality'],
                    'parent_id' => $category['parent_id'] ?? null,
                ]
            );
        }
        foreach($this->diagnosisParameters as $parameter){
            \DB::table('diagnosis_parameters')->insert(
                [
                    'id' => $parameter['id'],
                    'name' => $parameter['name'],
                    'category' => $parameter['category'] ?? null,
                    'cardinality' => $parameter['cardinality'],
                    'parent_id' => $parameter['parent_id'] ?? null,
                ]
            );
        }


    }
}
